### PR TITLE
feat: support tauri v2

### PR DESCRIPTION
**Pull request by ayangweb**
@lucasfernog Need you to continue to optimize, thanks🌹

### CODE REVIEW

**Comment by lucasfernog-crabnebula** [comment]
quite impressed with how far you got here, amazing work! i've been testing this on macOS and it's working well.. now we must verify Windows and Linux too

**Comment by ayangweb** [comment]
Ok, no problem, I have windows and Linux VMs, I'll help you test it in my free time!

**Comment by ayangweb** [comment]
It runs fine on windows!

https://github.com/user-attachments/assets/689c38bf-34c6-4d19-823a-6c09c129db3b

There is a warning on windows startup though, is this something that needs to be addressed?

iShot_2024-10-16_10 05 00

**Comment by lucasfernog** [comment]
i did notice the warning, it was there on the previous version too, that should be fine to adjust right @amr-crabnebula ?

**Comment by ayangweb** [comment]
The `tauri-plugin-drag-as-window` plugin only supports opening windows by dragging them to the left, the windows generated on the right do not open!

https://github.com/user-attachments/assets/f381b8f0-9faf-4b7e-8c05-5563db1b4e38

**Comment by lucasfernog** [comment]
I can see what's the problem tomorrow.. looks like it's a deadlock?

**Comment by ayangweb** [comment]
Linux works fine🥳

`tauri-plugin-drag`

https://github.com/user-attachments/assets/2956538c-20bd-4018-8b5c-0ba1d0793636

`tauri-plugin-drag-as-window`

https://github.com/user-attachments/assets/b2433979-3b4a-452b-85d6-02174cbea589

**Comment by amr-crabnebula** [comment]
> i did notice the warning, it was there on the previous version too, that should be fine to adjust right @amr-crabnebula ?

yeah feel free to fix it, it is just trying to read the `Result` stored in a static variable.

**Comment by lucasfernog-crabnebula** [comment]
@ayangweb i think you tested the main branch as the crates aren't even building yet on Linux and Windows 😂

**Comment by ayangweb** [comment]
> @ayangweb i think you tested the main branch as the crates aren't even building yet on Linux and Windows 😂

Sorry, I did forget to switch branches 🤣 I'll go back and re-run the test later!

**Comment by lucasfernog-crabnebula** [comment]
funny that i did the same thing 😂 i can also do some tests / try to fix the builds later

**Comment by ayangweb** [comment]
Windows works fine 🥳

The `tauri-plugin-drag-as-window` window doesn't show, I think it's a postions issue?

https://github.com/user-attachments/assets/529b983a-4e83-4873-a96e-9a09bc985b90

**Comment by ayangweb** [comment]
image

I'm not sure it's this one [pr](https://github.com/gtk-rs/gtk3-rs/pull/827) related to

**Comment by lucasfernog-crabnebula** [comment]
> Windows works fine 🥳
> 
> The `tauri-plugin-drag-as-window` window doesn't show, I think it's a postions issue?
> 
>  10.16.mov

you must drag to an empty space like the desktop, it's working well on my end

**Comment by lucasfernog-crabnebula** [comment]
I think we're good to go, this is impressive!!!!

**Comment by ayangweb** [comment]
> I think we're good to go, this is impressive!!!!

As I https://github.com/crabnebula-dev/drag-rs/pull/38#issuecomment-2415584246 this demo, it does have problems!

**Comment by ayangweb** [comment]
https://github.com/user-attachments/assets/d6b6ac98-edde-4df8-bcb1-c02ddea4c414

**Comment by ayangweb** [comment]
Every platform behaves differently, users just adapt themselves! 🤣

https://github.com/user-attachments/assets/094f8dd4-168a-468e-92f2-a190a6933a4e

**Comment by ayangweb** [comment]
No, I see that `x` and `y` are returned by `dragAsWindow`, without looking closely at the code I thought it was taken directly by the js

**Comment by lucasfernog-crabnebula** [comment]
> > I think we're good to go, this is impressive!!!!
> 
> As I [#38 (comment)](https://github.com/crabnebula-dev/drag-rs/pull/38#issuecomment-2415584246) this demo, it does have problems!

I couldn't reproduce it.. do you also face similar problems on the main branch?

**Comment by ayangweb** [comment]
> > > I think we're good to go, this is impressive!!!!
> > 
> > 
> > As I [#38 (comment)](https://github.com/crabnebula-dev/drag-rs/pull/38#issuecomment-2415584246) this demo, it does have problems!
> 
> I couldn't reproduce it.. do you also face similar problems on the main branch?

https://github.com/crabnebula-dev/drag-rs/pull/38#issuecomment-2415579762 It's the main branch.

**Comment by lucasfernog-crabnebula** [comment]
let's file a separate issue for it then, as i see this work as completed

**Comment by lucasfernog-crabnebula** [comment]
do you have a multi monitor setup? that might be the problem here, idk if the positioning work well in that case

**Comment by ayangweb** [comment]
I don't have a multi-display connected, so let's open a separate issue to handle it!

**Review by lucasfernog-crabnebula — APPROVED** [review]
truly amazing work!

**Comment by ayangweb** [comment]
I forgot to mention that I actually think we should create a new v2 branch merge!

**Pull request merged**
